name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Go application
      run: go build .
